### ISSUE TITLE
Dashboard for cronjob checking package integrity and availability [8pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/package-update-job#71]
As Thoth,
I want to run a periodic job,
so that I can detect python modules that have disappeared from an index
and so that I can keep my knowledge graph up to date.

** Context **

I, as Thoth, would like to keep my database of packages fresh and up2date. As packages might disappear from package indexes or get modified, we should keep track of such issues. Let's create a cronjob which queries Thoth's database of packages and checks their integrity and availability (available of packages as well as versions published on indexes).

seeAlso https://trello.com/c/LjJkHyeC

**Comment by KPostOffice** [comment]
@goern For this do you just want an idea of the number of packages being changed/removed per day or are you thinking of a web-page where you can actually query and see the status of individual packages and package versions?
