### ISSUE TITLE
Deploy cronjob for checking package integrity and availability [5pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/package-update-job#72]
As Thoth,
I want to run a periodic job,
so that I can detect python modules that have disappeared from an index
and so that I can keep my knowledge graph up to date.

** Context **

I, as Thoth, would like to keep my database of packages fresh and up2date. As packages might disappear from package indexes or get modified, we should keep track of such issues. Let's create a cronjob which queries Thoth's database of packages and checks their integrity and availability (available of packages as well as versions published on indexes).

seeAlso https://trello.com/c/8lmxhECt

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/thoth-application/blob/master/package-update/base/cronjob.yaml

I think this is already done
